version: '3.1'

services:
    mysql:
        image: mysql:8.1.0
        container_name: mysql_produccion
        env_file:
            - .env  # Ruta al archivo .env
        environment:
            MYSQL_ROOT_PASSWORD: espia123
        ports:
            - "3306:3306"
        volumes:
            - ./db_data_mysql:/var/lib/mysql
        restart: always
        networks:
            - my_network

    php:
        container_name: php_produccion
        env_file:
            - .env  # Ruta al archivo .env
        ports:
            - "9090:80"
        restart: always
        build: .
        volumes:
            - .:/var/www/html # live reload
        networks:
            - my_network

networks:
    my_network:
        driver: bridge
